/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/room.glb -o src/components/Room.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/room.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.imagetostl_mesh0_1.geometry} material={materials['Wall Side']} />
        <mesh geometry={nodes.imagetostl_mesh0_2.geometry} material={materials.Floor} />
        <mesh geometry={nodes.imagetostl_mesh0_3.geometry} material={materials.Roof} />
      </group>
      <mesh geometry={nodes.imagetostl_mesh1.geometry} material={materials.Table} position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.imagetostl_mesh2.geometry} material={materials.mat2} position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.imagetostl_mesh3.geometry} material={materials['Wall Side']} position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.imagetostl_mesh4_1.geometry} material={materials.Bed} />
        <mesh geometry={nodes.imagetostl_mesh4_2.geometry} material={materials.BedSheet} />
        <mesh geometry={nodes.imagetostl_mesh4_3.geometry} material={materials.BedLower} />
      </group>
      <group position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.imagetostl_mesh5_1.geometry} material={materials['Seat.001']} />
        <mesh geometry={nodes.imagetostl_mesh5_2.geometry} material={materials['Legs.001']} />
      </group>
      <group position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.imagetostl_mesh6_1.geometry} material={materials.Seat} />
        <mesh geometry={nodes.imagetostl_mesh6_2.geometry} material={materials.Legs} />
      </group>
      <group position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.imagetostl_mesh7_1.geometry} material={materials['Clip Board']} />
        <mesh geometry={nodes.imagetostl_mesh7_2.geometry} material={materials['Black Part']} />
      </group>
      <mesh geometry={nodes.imagetostl_mesh8.geometry} material={materials.Drawers} position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.imagetostl_mesh9.geometry} material={materials.mat9} position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.imagetostl_mesh10.geometry} material={materials['Material.002']} position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.imagetostl_mesh11_1.geometry} material={materials.Mug} />
        <mesh geometry={nodes.imagetostl_mesh11_2.geometry} material={materials.Black} />
        <mesh geometry={nodes.imagetostl_mesh11_3.geometry} material={materials.White} />
      </group>
      <mesh geometry={nodes.imagetostl_mesh12.geometry} material={materials.mat12} position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.imagetostl_mesh13.geometry} material={materials.Stand} position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.imagetostl_mesh14.geometry} material={materials.mat14} position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.imagetostl_mesh15_1.geometry} material={materials['Stool Legs']} />
        <mesh geometry={nodes.imagetostl_mesh15_2.geometry} material={materials['Stool Seats']} />
      </group>
      <group position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.imagetostl_mesh16_1.geometry} material={materials['Side Table']} />
        <mesh geometry={nodes.imagetostl_mesh16_2.geometry} material={materials.Inner} />
      </group>
      <mesh geometry={nodes.imagetostl_mesh17.geometry} material={materials.mat17} position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0, 0.839, -0.247]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.imagetostl_mesh0001_1.geometry} material={materials['Switch Board']} />
        <mesh geometry={nodes.imagetostl_mesh0001_2.geometry} material={materials.Plugs} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/room.glb')
